"use client";

import dynamic from 'next/dynamic';
import './globals.css'

const AppContextProvider = dynamic(() => import('@/components/appContext'), { ssr: false })
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body>{children}</body>
      </AppContextProvider>
    </html>
  )
}
